apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: flask-demo-prod
  namespace: prod
spec:
  project: platform
  source:
    repoURL: https://github.com/kickoffqi/aiops-agent
    targetRevision: main
    path: app/flask-demo
    helm:
      valueFiles:
        - values.yaml
        - envs/prod/values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
